db_file: "bot.db"

bot_url: "https://t.me/getpocket_client_bot"

messages:
  response:
    start: "Привет! Чтобы сохранять ссылки в своем Pocket аккаунте, для начала тебе необходимо дать мне на это доступ. Для этого переходи по ссылке:\n%s"
    already_authorized: "Ты уже авторизовался с помощью своего Pocket аккаунта. Присылай ссылку чтобы сохранить."
    unknown_command: "Я не знаю такой команды :("
    link_saved: "Ссылка успешно сохранена!"
  error:
    default: "Произошла неизвестная ошибка."
    invalid_url:  "Это невалидная ссылка."
    unable_to_save: "Не удалось сохранить ссылку в Pocket. Попробуйте пожалуйста позже."